services: 
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx

  nodejs_app:
    build: ./node_app
    container_name: node_app

  php_app: 
    build: ./php_app
    container_name: php_app

  go_app:
    build: ./go_app
    container_name: go_app


